### ISSUE TITLE
The block expand and collapese icons are the same

### ISSUE THREAD

**Issue by ahmadooka** [dracula/notepad-plus-plus#14]
The block expand (+) and collapse (-) icons are the same, just a square. Normally they should show - or +

![image](https://user-images.githubusercontent.com/18098410/54186497-d4b15a80-44ab-11e9-83e8-2c08e91dcaed.png)

**Comment by slodown** [comment]
Hey,
you need to change the following lines:
![2019-04-10_095603](https://user-images.githubusercontent.com/49473911/55861587-f2d7ac80-5b76-11e9-8e2a-2b56073689be.png)
This is the result:
![2019-04-10_100053](https://user-images.githubusercontent.com/49473911/55861888-a0e35680-5b77-11e9-8dc5-e2b4dbd7e108.png)
Best regards

**Comment by ukarim** [comment]
@ahmadooka it's by design ¯\_(ツ)_/¯
please use the solution suggested in the previous comment
