### ISSUE TITLE
Add additional instructions for Windows 7 users

### ISSUE THREAD

**Issue by hacknug** [dracula/notepad-plus-plus#18]
Just got this email from one of the theme's users. Can anyone confirm this is right?

In case it is, if someone can open a PR adding the additional instructions I'd be super thankful 🙏 

> Hello! Thanks for the Dracula theme. 
> I downloaded and installed it on Notepad ++. 
> But on my Windows 7 x-32 a completely different way of 
> installing the theme. 
> Your website: https://draculatheme.com/notepad-plus-plus/ 
> indicates that the Dracula.xml file should be copied to 
> % AppData% \ Notepad ++ \ themes, but in Windows 7 it should 
> be copied to % AppData % \ Roaming \ Notepad ++. 
> Please fix it. Thank you!

**Comment by ukarim** [comment]
% AppData% is an environment variable. On Windows 7 this variable points to C:\Users\<username>\AppData\Roaming directory.

**Comment by hacknug** [comment]
Don't understand what the issue was then 🤔 Thanks for clarifying!
