### ISSUE TITLE
Wrong path in Notepad++ page on draculatheme.com.

### ISSUE THREAD

**Issue by gluons** [dracula/notepad-plus-plus#2]
[![dracula a dark theme for notepad and more](https://cloud.githubusercontent.com/assets/4688092/24439060/09f2ce6c-1476-11e7-82a5-a49bcfc4d92b.png)](https://draculatheme.com/notepad-plus-plus/)

Path `%AppData%\Roaming\Notepad++\themes` is wrong.

`%AppData%` is `C:\Users\<user name>\AppData\Roaming`.
So, it should be `%AppData%\Notepad++\themes`.

**Comment by zenorocha** [comment]
Hey @ukarim, can you review that information and make a pull request on https://github.com/dracula/dracula.github.io?

Thanks!

**Comment by ukarim** [comment]
done https://github.com/dracula/dracula.github.io/pull/32

**Comment by zenorocha** [comment]
Thanks!
