### ISSUE TITLE
ReadMe/Install irritation

### ISSUE THREAD

**Issue by S4MT3K** [dracula/notepad-plus-plus#21]
I just want to let you know, that the Installation path for the xml of Notepad++ is wrong. 

you Describe appdata/notepad++ but its located in appdata/roaming/notepad++

Maybe you want to change it. i was smart enough to figure it out, but maybe some certain people will hang on this point. 

Regards S4MT3K

PS: On the description on the Website

**Comment by ukarim** [comment]
@S4MT3K %AppData% is just an environment variable (for example, on Windows 7 it points to C:\Users\ukarim\AppData\Roaming).
I've just opened pr https://github.com/dracula/dracula.github.io/pull/81 with comments about %AppData%
