### ISSUE TITLE
Wrong folder for themes on win10

### ISSUE THREAD

**Issue by aBnormaLz** [dracula/notepad-plus-plus#28]
Actually the correct folder is %AppData%\Roaming\Notepad++\themes

I see that there is a closed issue for this, so maybe the folder depends on windows version :)

https://github.com/dracula/notepad-plus-plus/issues/2

**Comment by ukarim** [comment]
%AppData% is platform dependent env variable.
More info here https://github.com/dracula/dracula.github.io/pull/81

**Comment by zenorocha** [comment]
This has been fixed now: https://github.com/dracula/notepad-plus-plus/commit/03d2dc3640296a285b9d88864821412915e0db95

Thanks for your patience!
