### ISSUE TITLE
Some GlobalStyles WidgetStyle tags aren't present

### ISSUE THREAD

**Issue by lucknaumann** [dracula/notepad-plus-plus#29]
Noticed that a number of GlobalStyles WidgetStyle tags aren't present like they are in other themes.
What's up with that?

- "Smart HighLighting"
- "Find Mark Style"
- "Mark Style 1"
- "Mark Style 2"
- "Mark Style 3"
- "Mark Style 4"
- "Mark Style 5"
- "Active tab unfocused indicator"
- "Active tab text"
- "Inactive tabs"

**Comment by ukarim** [comment]
@lucknaumann when I just started dracula for npp I was ok with default behaviour of this props.
Anyway contributions are very welcome)

**Comment by lucknaumann** [comment]
OK. I didn't realize that was the default. Thanks for your response and efforts! =)
