### ISSUE TITLE
Darken white space color

### ISSUE THREAD

**Issue by dimejo** [dracula/notepad-plus-plus#35]
Please consider changing the white space color to something darker as it currently is way too bright which makes it hard to read text. I would suggest using #6272A4 (comment color accoring to [spec.draculatheme.com](https://spec.draculatheme.com/#sec-Standard)).
<img width="860" alt="dracula_white-space_old" src="https://user-images.githubusercontent.com/25005220/104189945-a9875180-541b-11eb-959f-ff7bf746a8b6.png">
<img width="860" alt="dracula_white-space_new" src="https://user-images.githubusercontent.com/25005220/104189957-ad1ad880-541b-11eb-9b63-3a167d814367.png">

**Comment by luxonauta** [comment]
Hi @dimejo, good suggestion! 😁
I couldn't replicate your example, but this issue seems to be resolved.
I'm not familiar with this language, so it might be my mistake. 😅
Please let me know if this is still an issue and if you would like to do a PR with this solution.

**Comment by dimejo** [comment]
> I couldn't replicate your example, but this issue seems to be resolved.
> I'm not familiar with this language, so it might be my mistake. 😅

Display of symbols can be enabled/disabled globally (Main Menu -> View -> Show Symbol) for all languages.

I have created a PR with the proposed fix.
