### ISSUE TITLE
Selected text colour

### ISSUE THREAD

**Issue by brccabral** [dracula/notepad-plus-plus#36]
I feel that "Selected text colour" doesn't contrast with background.
This feels better for me
`<WidgetStyle name="Selected text colour" styleID="0" bgColor="03AFD3" fgColor="F8F8F2" fontStyle="0" />`

**Comment by luxonauta** [comment]
Hi @brccabral, thanks for the suggestion! 😁
All [Dracula themes](https://draculatheme.com/) must follow the same [specs](https://spec.draculatheme.com/); This ensures that different projects are consistent with each other.
So it is not possible to be changing that colour. 😅
