### ISSUE TITLE
TypeScript Syntax Highlighting doesn't work

### ISSUE THREAD

**Issue by hichemfantar** [dracula/notepad-plus-plus#37]
Notepad++ v8.1.4 32bit, Typescript files appear all in white text.
It works when using the default theme.
![image](https://user-images.githubusercontent.com/34947993/133910979-adc63fe4-b165-4907-bbca-f261a4b02638.png)

**Comment by luxonauta** [comment]
Hi @hichemfantar! 😁
Notepad++ does not **currently** support Typescript, as you can check in the [list of supported programming languages](https://npp-user-manual.org/docs/programing-languages/).
Unfortunately, this makes it impossible to create a syntax highlighting using Dracula's specs.
