### ISSUE TITLE
String color inconsistent between projects

### ISSUE THREAD

**Issue by brccabral** [dracula/notepad-plus-plus#38]
Hi everyone,
Strings in Visual Studio Code and SQL Developer are yellow F1FA8C, but in Notepad++ are red FF5555.
Should different projects be consistent with each other or not?
Thanks,
Bruno

**Comment by zenorocha** [comment]
@ukarim do you want to give it shot?

**Comment by ukarim** [comment]
@zenorocha I no longer have access to Windows machine and I cannot properly test new changes.
I already added _maintainer-wanted _ topic to repo. Probably it will be good to add _call for maintainers_ in project readme
