### ISSUE TITLE
Green all over

### ISSUE THREAD

**Issue by brccabral** [dracula/notepad-plus-plus#45]
Notepad++ has green colors in almost everything. Compare with VS Code, for example. Class names should be cyan, variables should be "Foregraound" (almost white), etc... 

![image](https://user-images.githubusercontent.com/130455/160954525-733679d1-01b3-4708-a443-590926670d08.png)

**Comment by luxonauta** [comment]
😓 This is a problem I want to solve! Are you interested in creating a PR? 🤔
