### ISSUE TITLE
please add color to "EOL custom color" in Notepad++ new version 8.4.4

### ISSUE THREAD

**Issue by JergenRoss** [dracula/notepad-plus-plus#46]
v 8.4.4 new updated

I want to add color EOL custom color a.k.a `CR` `LF`.
 
![image](https://user-images.githubusercontent.com/59808813/182593518-579cd59d-3b54-45ce-96e6-f1d45ba89ecb.png)

![image](https://user-images.githubusercontent.com/59808813/182593335-5ba14e95-6a2d-46d7-bfc7-1c8d95cee30b.png)

make sure update your theme. thanks

**Comment by luxonauta** [comment]
Are you interested in creating a PR? 🤔

**Comment by JergenRoss** [comment]
yes because too much white, but now fixed by myself using edit xml.
