### ISSUE TITLE
Theme and dark mode

### ISSUE THREAD

**Issue by AzazelHD** [dracula/notepad-plus-plus#48]
![imagen](https://github.com/dracula/notepad-plus-plus/assets/47080553/d387f385-cc89-4083-b12c-061dc4f2d7a6)
![imagen](https://github.com/dracula/notepad-plus-plus/assets/47080553/207abee0-cef1-49a7-ab58-1c2f28aed9ff)

Hello. Is there a dracula them with original colors for the dark mode? When activating dark mode, to make UI dark, colors change

**Comment by luxonauta** [comment]
Hi 👋🏻, we will still work on an update of the theme. But this should stay the same as how the theme behaves. Thank you for creating this Issue.

**Comment by xan2622** [comment]
Any update regarding the dark mode support?

**Comment by luxonauta** [comment]
Not yet
