### ISSUE TITLE
"Selected text colour" and "Current line background colour" bgColor are same resulting in loss of functionality

### ISSUE THREAD

**Issue by djazpurua711** [dracula/notepad-plus-plus#57]
Propose to update bgColor to purple ([#BD93F9](https://draculatheme.com/contribute)) for ["Selected text colour"](https://github.com/dracula/notepad-plus-plus/blob/master/Dracula.xml#L534) to distinguish between selected text and current line

**Comment by quincynyan** [comment]
1up!

**Comment by quincynyan** [comment]
#58 should fix it
